CREATE TABLE CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    EMAIL VARCHAR(128) UNIQUE,
    PHONE VARCHAR(32),
    ADDRESS VARCHAR(256),
    CITY VARCHAR(64),
    STATE CHAR(2),
    ZIPCODE VARCHAR(12)
);

CREATE TABLE ORDERS (
    ORDER_ID VARCHAR(16) PRIMARY KEY,
    CUSTOMER_ID BIGINT,
    ORDER_VALUE FLOAT
);


ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);
